name: Reusable - ESLint

on:
  workflow_call:

    inputs:

      service-name:
        description: "Service Name"
        required: true
        type: string

      runner:
        description: "Runner label"
        required: false
        type: string
        default: ubuntu-latest

      node-version:
        description: "Node.js version"
        required: false
        type: string
        default: "18"


jobs:

  ESLint-Job:
    name: ESLint
    runs-on: ${{ inputs.runner }}

    permissions:
      contents: read
      security-events: write

    steps:

      # ============================================================
      # Checkout
      # ============================================================

      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0


      # ============================================================
      # Setup Node.js
      # ============================================================

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
          

      # ============================================================
      # Install Dependencies
      # ============================================================

      - name: Install frontend dependencies
        run: npm install    # npm ci
        

      # ============================================================
      # ESLint Scan
      # ============================================================

      - name: Run ESLint
        run: |
          npx eslint . \
            --ext js,jsx,ts,tsx \
            --report-unused-disable-directives \
            --max-warnings 0 \
            --config .eslintrc.cjs \
            --format sarif \
            --output eslint-${{ inputs.service-name }}.sarif       # .json
            

      # ============================================================
      # Upload ESLint Scan SARIF report to Github
      # ============================================================

      - name: Upload ESLint SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: eslint-${{ inputs.service-name }}.sarif
          category: eslint

          
